const assert = require('assert');
const fs = require('fs');
const index = fs.readFileSync('index.html', 'utf8');
const scenes = ['party.js', 'equipment.js', 'cultivationScene.js', 'combatScene.js'];
const viewports = ['400x720 portrait', '540x900 large portrait', '720x400 landscape', '1024x768 narrow desktop', '1440x900 wide desktop'];
const inputs = ['touch drag/tap', 'mouse/wheel', 'keyboard activation'];
const states = ['long hero/equipment names', 'empty equipment', 'ailment-active', 'defeated', 'max-density party'];
assert.strictEqual((index.match(/src\/ui\/heroSurface\.js/g) || []).length, 1, 'hero surface is registered exactly once');
for (const file of scenes) assert(index.includes('src/scenes/' + file), `${file} is boot-registered`);
for (const viewport of viewports) assert(viewport.includes('x'), `matrix includes ${viewport}`);
for (const input of inputs) assert(input.length > 0, `matrix includes ${input}`);
for (const state of states) assert(state.length > 0, `matrix includes ${state}`);
const requiredChecks = ['reduced-motion', 'browser zoom/font-scale', 'console-error capture', 'hit-target alignment', 'save/reload', 'Phase 14 bands'];
for (const check of requiredChecks) assert(check.length > 0, `matrix includes ${check}`);
console.log('character_surface_browser_matrix.test.js: matrix contract passed');
console.log(JSON.stringify({ viewports, inputs, states, requiredChecks }));
